# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MCHSmartCity' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MCHSmartCity

  pod 'youtube-ios-player-helper'
  pod 'FancyGradient'
  
  target 'MCHSmartCityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MCHSmartCityUITests' do
    # Pods for testing
  end

end
